"""empty message

Revision ID: b02f2f7c48a9
Revises: 
Create Date: 2022-03-21 02:56:49.597432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02f2f7c48a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_name', sa.String(length=200), nullable=False),
    sa.Column('sprint_desc', sa.Text(), nullable=False),
    sa.Column('sprint_rank', sa.Integer(), nullable=False),
    sa.Column('sprint_estm', sa.Integer(), nullable=False),
    sa.Column('sprint_create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_sprint_name'), 'sprint', ['sprint_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_dev', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_desc', sa.Text(), nullable=False),
    sa.Column('task_rank', sa.Integer(), nullable=False),
    sa.Column('task_state', sa.Integer(), nullable=True),
    sa.Column('task_estm', sa.Integer(), nullable=False),
    sa.Column('task_create_at', sa.DateTime(), nullable=True),
    sa.Column('task_taken_at', sa.DateTime(), nullable=True),
    sa.Column('task_done_at', sa.DateTime(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sprint_sprint_name'), table_name='sprint')
    op.drop_table('sprint')
    # ### end Alembic commands ###
